
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import models.Archivo;
import static models.Archivo.archivos;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sebax
 */
public class Produccion extends javax.swing.JFrame {
    DefaultTableModel tbl = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column){
            return false;
        }
    };
    /**
     * Creates new form Produccion
     */
    public Produccion() {
        initComponents();
        this.campoRecNo.setText("-1");
        this.LabelRecNo.setVisible(false);
        this.campoRecNo.setVisible(false);
        Archivo.llenarArchivos();
        setModelo();
        setDatos();
    }
        public static void autor62731(){
        System.out.println("Sebastian Nah Cahuich");
        System.out.println("62731");
        System.out.println("al062731@uacam.mx");
    }
        private void setModelo(){
        String[] tblcabecera = {"N","ID","Codigo", "Nombre", "Actvidad","Responsable","Uso"};
        tbl.setColumnIdentifiers(tblcabecera);
        tblArchivo.setModel(tbl);
    }
        private void setDatos(){
        Object[] datos = new Object[tbl.getColumnCount()];
        int i = 0;
        tbl.setRowCount(0);
        for (Archivo Archivo : archivos) {
            datos[0] = i;
            datos[1] = Archivo.getID();
            datos[2] = Archivo.getCodigo();
            datos[3] = Archivo.getNombre();
            datos[4] = Archivo.getActividad();
            datos[5]= Archivo.getResponsable();
            datos[6]= Archivo.getUso();
            i++;
            tbl.addRow(datos);
        }
    }
        private void limpiarCampos(){
        this.campoID.setText("");
        this.campoNom.setText("");
        this.campoAct.setText("");
        this.campoResponsable.setText("");
        this.campoUso.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelRecNo = new javax.swing.JLabel();
        campoRecNo = new javax.swing.JTextField();
        LabelID = new javax.swing.JLabel();
        LabelNombre = new javax.swing.JLabel();
        LabelActividad = new javax.swing.JLabel();
        LabelResponsable = new javax.swing.JLabel();
        LabelUso = new javax.swing.JLabel();
        campoID = new javax.swing.JTextField();
        campoNom = new javax.swing.JTextField();
        campoAct = new javax.swing.JTextField();
        campoResponsable = new javax.swing.JTextField();
        campoUso = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblArchivo = new javax.swing.JTable();
        bttnCancelar = new javax.swing.JButton();
        bttnAñadir = new javax.swing.JButton();
        bttnEliminar = new javax.swing.JButton();
        bttnActualizar = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        LabelCodigo = new javax.swing.JLabel();
        campoCodigo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelRecNo.setText("RecNo");

        LabelID.setText("ID");

        LabelNombre.setText("Nombre");

        LabelActividad.setText("Actividad");

        LabelResponsable.setText("Responsable");

        LabelUso.setText("Uso");

        tblArchivo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblArchivo);

        bttnCancelar.setText("Cancelar");
        bttnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCancelarActionPerformed(evt);
            }
        });

        bttnAñadir.setText("Añadir");
        bttnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnAñadirActionPerformed(evt);
            }
        });

        bttnEliminar.setText("Eliminar");
        bttnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnEliminarActionPerformed(evt);
            }
        });

        bttnActualizar.setText("Actualizar");
        bttnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnActualizarActionPerformed(evt);
            }
        });

        jButton5.setText("Exportar");

        LabelCodigo.setText("Codigo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelResponsable)
                            .addComponent(LabelUso)
                            .addComponent(LabelActividad)
                            .addComponent(LabelNombre)
                            .addComponent(LabelID)
                            .addComponent(LabelCodigo))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoID, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                                    .addComponent(campoCodigo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton5))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoUso, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoAct, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(campoNom, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(bttnCancelar)
                        .addGap(215, 215, 215)
                        .addComponent(bttnAñadir)
                        .addGap(159, 159, 159)
                        .addComponent(bttnEliminar)
                        .addGap(107, 107, 107)
                        .addComponent(bttnActualizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1307, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelRecNo)
                .addGap(18, 18, 18)
                .addComponent(campoRecNo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelRecNo)
                    .addComponent(campoRecNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelCodigo)
                            .addComponent(campoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LabelID)
                            .addComponent(campoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jButton5)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNombre)
                    .addComponent(campoNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelActividad)
                    .addComponent(campoAct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelResponsable)
                    .addComponent(campoResponsable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelUso)
                    .addComponent(campoUso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bttnCancelar)
                            .addComponent(bttnAñadir))
                        .addGap(53, 53, 53)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 29, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bttnEliminar)
                            .addComponent(bttnActualizar))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnAñadirActionPerformed
        // TODO add your handling code here:
        int recNo = Integer.parseInt(this.campoRecNo.getText().trim());
        int ID = Integer.parseInt(this.campoID.getText().trim());
        String Codigo = this.campoCodigo.getText();
        String actividad = this.campoAct.getText();
        String nombre = this.campoNom.getText();
        String responsable = this.campoResponsable.getText();
        String uso = this.campoUso.getText();
        

        if (recNo == -1) {
            Archivo.insertarArchivos(ID,Codigo,nombre,actividad,responsable,uso);
        } else {
            
            Archivo.ActualizarArchivos(recNo,ID,Codigo,nombre,actividad,responsable,uso);
            this.bttnActualizar.setSelected(false);
            
        }
        setDatos();
        limpiarCampos();
    }//GEN-LAST:event_bttnAñadirActionPerformed

    private void bttnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCancelarActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_bttnCancelarActionPerformed

    private void bttnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnEliminarActionPerformed
        // TODO add your handling code here:
        int filaActual = tblArchivo.getSelectedRow();
        System.out.println(tblArchivo.getSelectionModel().getClass());
        if (filaActual != -1){
            System.out.println(filaActual);
            //dtmMunicipios.removeRow(filaActual);
            System.out.println(archivos);
            Archivo.eliminarArchivos(filaActual);
            setDatos();

        }
    }//GEN-LAST:event_bttnEliminarActionPerformed

    private void bttnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnActualizarActionPerformed
        // TODO add your handling code here:
        int filaActual = tblArchivo.getSelectedRow();
    
        if (filaActual != -1) {
        String recNo = tblArchivo.getValueAt(filaActual, 0).toString();
        String Codigo = tblArchivo.getValueAt(filaActual, 2).toString();
        String ID = tblArchivo.getValueAt(filaActual, 1).toString();
        String Nombre = tblArchivo.getValueAt(filaActual, 3).toString();
        String Actividad = tblArchivo.getValueAt(filaActual, 4).toString();
        String Responsable = tblArchivo.getValueAt(filaActual, 5).toString();
        String Uso = tblArchivo.getValueAt(filaActual, 6).toString();

        campoRecNo.setText(recNo);
        campoNom.setText(Nombre);
        campoID.setText(ID);
        campoAct.setText(Actividad);
        campoCodigo.setText(Codigo);
        campoUso.setText(Uso);
        campoResponsable.setText(Responsable);
        
        } else {
        JOptionPane.showMessageDialog(this, "Debe seleccionar una fila.", "Error", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_bttnActualizarActionPerformed
} 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Produccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Produccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Produccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Produccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Produccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelActividad;
    private javax.swing.JLabel LabelCodigo;
    private javax.swing.JLabel LabelID;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelRecNo;
    private javax.swing.JLabel LabelResponsable;
    private javax.swing.JLabel LabelUso;
    private javax.swing.JButton bttnActualizar;
    private javax.swing.JButton bttnAñadir;
    private javax.swing.JButton bttnCancelar;
    private javax.swing.JButton bttnEliminar;
    private javax.swing.JTextField campoAct;
    private javax.swing.JTextField campoCodigo;
    private javax.swing.JTextField campoID;
    private javax.swing.JTextField campoNom;
    private javax.swing.JTextField campoRecNo;
    private javax.swing.JTextField campoResponsable;
    private javax.swing.JTextField campoUso;
    private javax.swing.JButton jButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblArchivo;
    // End of variables declaration//GEN-END:variables
}
